# Products
productDictionary = {   # Variable name                     # Product cost      # Enchants  # Checkboxes                                                                                                # Multiple selection
    "Sword":           {"variableName": "swordNumber",      "productCost": 2,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Sweeping Edge 3", "Looting 3", "Knockback 2", "Fire aspect 2"], "multipleSelection": [ ["Sharpness 5", "Smite 5", "Bane of Arthropods 5" ] ] } },
    "Pickaxe":         {"variableName": "pickaxeNumber",    "productCost": 3,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Efficiency 5"],                                                 "multipleSelection": [ ["Silk touch", "Fortune 3"] ] } },
    "Shovel":          {"variableName": "shovelNumber",     "productCost": 1,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Efficiency 5"],                                                 "multipleSelection": [ ["Silk touch", "Fortune 3"] ] } },
    "Axe":             {"variableName": "axeNumber",        "productCost": 3,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Efficiency 5"],                                                 "multipleSelection": [ ["Silk touch", "Fortune 3"] ] } },
    "Hoe":             {"variableName": "hoeNumber",        "productCost": 2,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Efficiency 5"],                                                 "multipleSelection": [ ["Silk touch", "Fortune 3"] ] } },
    "Helmet":          {"variableName": "helmetNumber",     "productCost": 5,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Thorns 3", "Respiration 3", "Aqua affinity"],                   "multipleSelection": [ ["Protection 4", "Fire Protection 4", "Blast Protection 4", "Projectile Protection 4"] ] } },
    "Chestplate":      {"variableName": "chestplateNumber", "productCost": 8,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Thorns 3"],                                                     "multipleSelection": [ ["Protection 4", "Fire Protection 4", "Blast Protection 4", "Projectile Protection 4"] ] } },
    "Leggings":        {"variableName": "leggingsNumber",   "productCost": 7,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Thorns 3"],                                                     "multipleSelection": [ ["Protection 4", "Fire Protection 4", "Blast Protection 4", "Projectile Protection 4"] ] } },
    "Boots":           {"variableName": "bootsNumber",      "productCost": 4,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Thorns 3", "Soul speed 3", "Feather falling 4"],                "multipleSelection": [ ["Protection 4", "Fire Protection 4", "Blast Protection 4", "Projectile Protection 4"], ["Frost walker 2", "Depth strider 3"] ]} },
    "Crossbow":        {"variableName": "crossbowNumber",   "productCost": 0,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Quick charge 3"],                                               "multipleSelection": [ ["Piercing 4", "Multishot"] ] } },
    "Bow":             {"variableName": "bowNumber",        "productCost": 0,   "enchants": {"checkboxes": ["Unbreaking 3", "Power 5", "Punch 2", "Flame"],                                             "multipleSelection": [ ["Mending", "Infinity"] ] } },
    "Shears":          {"variableName": "shearsNumber",     "productCost": 0,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Efficiency 5"],                                                 "multipleSelection": [ [ ] ] } },
    "Flint&Steel":     {"variableName": "flintSteelNumber", "productCost": 0,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3"],                                                                 "multipleSelection": [ [ ] ] } },
    "Shield":          {"variableName": "shieldNumber",     "productCost": 0,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3"],                                                                 "multipleSelection": [ [ ] ] } },
    "Fishing Rod":     {"variableName": "fishingRodNumber", "productCost": 0,   "enchants": {"checkboxes": ["Mending", "Unbreaking 3", "Luck of the sea 3", "Lure 3"],                                  "multipleSelection": [ [ ] ] } },
    "Elytra":          {"variableName": "elytraNumber",     "productCost": 15,  "enchants": {"checkboxes": ["Mending", "Unbreaking 3"],                                                                 "multipleSelection": [ [ ] ] } },
}